# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main



steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


 
- task: AzureCLI@2
  inputs:
    azureSubscription: 'LB22VM'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
          az vm start 
          --name luisVm
          --resource-group LB
      
          az vm stop 
          --name luisVm
          --resource-group LB