
      azureSubscription: 'LB22VM'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |

        # Start the VM
        az vm start 
            --name luisVm
            --resource-group LB
        
        # Stop the VM
        az vm stop 
            --name luisVm
            --resource-group LB

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

