# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

 - task: AzureCLI@2
   inputs:
    azureSubscription: 'LB22VM'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
  
      # Start the VM
      az vm start 
          --name luisVm
          --resource-group LB
      
      # Stop the VM
      az vm stop 
          --name luisVm
          --resource-group LB